```{r echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(knitr)
source("tech_report_table.R")
```

# **INFO201 FINAL PROJECT | Technical Report**  

**Project Code Name:** Global Terrorism  
**Authors:** Joseph Altamira, Jazmynn Combes-Troyer, Dorothy Lu

**Affiliation:** Info-201: Technical Foundations of Informatics  
The Information School  
University of Washington  
Autumn 2019  

## 1.0 INTRODUCTION PROBLEM SITUATION  
### 1.1 Problem Situation:

Terrorism is the unlawful and systematic use of violence against a state, country, or group of people, motivated by various ideologies, as a form of political coercion. Global acts of terrorism have impacted hundreds, thousands, and millions of people throughout history in social, economic, and political ways.  

### 1.1.1 Setting

Terrorism occurs on local, national, and international levels. Take - for instance - the white supremacist attack at the "Unite the Rally" attack in 2019, which occurred on US soil in Charlottesville, VA by Americans. This act of terrorism occurred on a more local level. Another example is the infamous al-Qaeda attack on the USA on September 11, 2001, which was a national terrorist attack. On an international level, one can look back on World War II and the Holocaust, which mainly targeted Jewish populations in Western Europe.  

### 1.1.2 Stakeholders

_Direct stakeholders_ include political entities (i.e. a government, political figure, or organization), both as targets and instigators. As instigators, political entities plan and execute attacks against other states, nations, other political groups, or specific political figures to further some political, religious, or other ideological objective. As targets, these political entities suffer damage from their attackers which may include death, injury, and political and economic harm.  

_Indirect stakeholders_ include civilians residing in or around the targeted person, group, or nation. These civilians are typically citizens of a state and are not direct or intended targets. Civilians may suffer personal loss via death or injury of themselves or loved ones as well as property damage or socioeconomic difficulties that may result from damage sustained from main stakeholders (such as governments or major political leaders).

### 1.1.3 Values and Tension: 

The typical values and tensions that drive terrorism involve disagreements in religious, political, and economic perspectives. Although the target types (i.e. individual, government, organization) of terrorist attacks are fairly diverse, it seems that a large percentage of attacks target governments and private property. These attacks cause government workers and general populations with a significant form of capital (money) fear for their well-being, which ultimately affects their quality of life.  

### 1.1.4 General Issues

The general issues at stake are the health and well-being of individuals in terror-stricken countries. Terrorism is an extreme way of expressing a political disagreement and it affects individuals, communities, and societies on multiple levels. Aside from the obvious physical and psychological impacts on direct victims, terrorism causes deep-rooted fear and insecurity within affected populations. These feelings of fear and insecurity can lead to larger social and economic issues within affected populations, which is evident in political uprisings, economic depressions, and social movements.  

### 1.1.5 Policy and Ethics

Terrorism is a result of political, religious, and other ideological tensions as well as differing fundamental values between different groups of people. This may include and affect political policies (regarding national security, political interference with other states and nations, and use of military forces) and humanitarian ethics (for example, those ethics and policies imposed and established by the United Nations). Current policies in place can also drive acts of terrorism as some ideological groups may disagree with those policies and execute acts of terrorism as a way to express their dissent and push their own ideological agendas.  

### 1.2 What is the Problem?

Acts of terrorism are violent and often ineffective ways of furthering a political or ideological agenda. Hundreds, thousands, and even millions of innocent civilians suffer as a result of terroristic attacks (i.e. the Boston Marathon Bombing, 9/11, the Pulse Nightclub shooting in Orlando, etc.). Whenever terrorist attacks occur, people often focus on the specific targets of the attacks. However, the attacks can be a significant source of instability for their surroundings, namely the civilians around the targeted person, entity, or area. Furthermore, terrorist attacks inflict damage that most people overlook such as property damage and damage to infrastructure that affect the daily lives of civilians. The problem is that most people do not realize how prevalent and common terrorist attacks are, who they affect beyond the intended target, and where many of these attacks occur.

### 1.2.1 Why Does It Matter?

Terrorism affects individuals, communities, and societies on multiple levels. Aside from the obvious physical and psychological impacts on direct victims of terrorism, terrorism causes deep-rooted fear and insecurity within affected populations. This problem is pertinent for any civilian or member of society as it is difficult to predict when or where the next attack will occur. Therefore, it is important to be aware of the ways in which one can be affected and to potentially prepare ways in which to respond. It is also important in order to be an informed citizen and to be aware of global issues. 

### 1.3 How Will it be Addressed?

The sensitive subject of terrorist attacks will be addressed by bringing attention to the number of terrorist attacks that have occurred, where they occurred, and who and what was affected. By gaining awareness of these aspects of terrorism and finding correlations between various data about those attacks (date, location, cause, etc.), we can raise awareness and educate the public about terrorism and about targeted regions that are not widely publicized by the media.

### 1.3.1 Data Wrangling and Info Viz

Our main dataset is very robust. It contains a great deal of information on the number of terror attacks throughout the last forty years. The dataset will be reduced in size to accommodate the size limits for files that can be pushed to GitHub as well as for the ease of loading in the data for wrangling and analysis. Adjusted datasets will include only relevant columns that are important for the data visualizations that provide insights into our research questions. It is unlikely that columns using strings as an input will be selected. Extreme values will be found using functions in dplyr. Along with extremes, all attacks will be displayed on a map for our information visualization. This data visualization will help explain that terrorism is not as rare as people may think.

### 1.3.2 Intended Audience

Government officials, journalists, and data analysts with a focus on national security are most likely the types of users to which this project will appeal or interest. However, this project and dataset can be used by most anyone. Our goal is to be able to initiate a discourse about this issue, and dissuade people from viewing this issue as taboo or too sensitive to discuss. People ought to see this in a light where people’s emotions are not manipulated or heavily influenced by journalists’ biases and political views.

### 1.4 Previous Work
There are multiple existing organizations, researchers, and educators dedicated to studying global terrorism, its effects on international relations, and potential prevention strategies. One example is the organization and team of researchers from which the dataset was created: the Study of Terrorism and Responses to Terrorism (START) at the University of Maryland.


### 1.5 Building on Previous Work
Rather than focusing on various aspects of terrorism in detail and at large, this project will focus primarily on individuals and impacts on fundamental parts of society such as government. We hope to gain more insight on how unintended stakeholders - namely civilians - are impacted by small and large scale attacks.  

### 1.6 Who Cares?
Those who may have special interest and concern about this issue include:   

- Humanitarians that wish to bring attention to affected populations in order to secure resources and provide aid to help rebuild damaged societies in terms of buildings and infrastructure, mental and physical health and well-being, and general social and political peace  

- Government officials concerned with national security through policy, armed forces, defense, and international relations


### 1.6.1 Why Do Others Care?
It is important to raise awareness about this issue in order to promote change, educate the public, and facilitate discussions about ideological differences in order to promote peace and understanding or, at the very least, acceptance. We realize that many issues and deep-rooted disagreements are highly complex (i.e. the Syrian War and extremist groups in the Middle East) and cannot be settled by mere discussion. However, it is still important to be informed in the event that  

### 1.6.2 We Care
Why do you care about this problem and what motivates you to work on it? 
The members of our group, like many Americans and other citizens around the world, is generally uninformed about both small and large scale terrorist attacks that have happened in the last few decades. We are interested in this topic because we would like to learn more about how these attacks affect humanitarian and movements around the world and how they could potentially affect us if we as a community, state, or nation were to become the next target of an attack.


## 2.0 RESEARCH QUESTIONS 
Generally speaking, the project will explore the impact of global terrorism in individuals and societies. Impacts on individuals can be operationalized as the number of injuries, casualties, property damage, and personal losses. Impacts on societies can include the type, scale, and target of the attack, especially if it was a large scale attack on a major leading political entity. Questions include:  

- Which countries suffered from the most civilian casualties by various attack types?  
- Does attack type and target impact the number of civilians impacted by the terrorist event?  
- How do different attack types impact the severity of damage sustained by individuals through personal injury or property damage? (Focus on personal death and injury)  

The **overarching research question** for this project is: Were individuals in different countries and  regions impacted differently, and how?  

- The question of whether individuals were impacted differently is measured by the number of deaths and injuries sustained by individuals in different countries
- The question of how individuals were impacted deals with the type of attack that was used against the targeted country  


## 3.0 THE DATA SET(S)   

The dataset that will be used throughout this project is called  “Global Terrorism Database” from kaggle.com. It lists over 180,000 terrorist attacks from 1970 to 2017. The GTD contains more than 100 variables, using information from media outlets/articles that are not classified. However, the current dataset is too large for github. To resolve this, certain rows were removed such that the project will focus only on the years between and including 2000 to 2017.


### 3.1 About the Data Set

**Who created it?**  
The database was created and maintained by researchers at the National Consortium for the Study of Terrorism and Responses to Terrorism (START) at the University of Maryland. Those researchers are also partnered with the Pinkerton Global Intelligence Service (PGIS).  

**Why was it created?**  
It was created to identify the risk of terrorism for clients of the PGIS.  

**Where did you access it?** 
The dataset can be accessed from https://www.kaggle.com/START-UMD/gtd or https://data.world/data-society/global-terrorism-data  

**What represents an “observation”?**   
An observation is a documented terrorist attack. This can come from a wire service, government reports, and major international papers. 

**What “variables” does each observation have?** 
There are roughly 135 variables. The top three we are most interested in are casualties, target of attack, and type of attack.

**How big is the data set? If it is a subset of a larger data set, how was the sub-set created?** 
Massive. Well over 180,000 recorded data. Each observation having more than 100 variables to describe the events.

**If the data set represents people, who has been included and who has been excluded?**  
_Included:_ Those impacted by an attack, such as private land-owners, government officials, and civilians. 

_Excluded:_ There are some countries that do not have a high number of attacks, it is possible for them to be excluded on the sole fact that they did have any observations that are recorded.


### 3.2 Data Set Strengths and Weaknesses

Envisioning cards were deployed to evaluate the strengths and weaknesses of the Global Terrorism Dataset. See Appendix 3: Use of Envisioning Cards.  

### 3.2.1 Dataset Strengths  
One of the biggest strengths of the global terrorism dataset is that it is incredibly large and robust. It includes data on terrorist attacks from 1970 to 2017. The dataset contains roughly 135 features on various aspects of the terrorist attacks such as attack and target type, whether the attack was “successful,” property damage sustained from the attack, location, and much more. The robustness of this dataset allows for the consideration of lots of different potential research questions and insights.  

### 3.2.2 Dataset Weaknesses  
Although the dataset provides a wide variety of features, not every entry has significant or meaningful information. In other words, one weakness is that the dataset has a lot of NA values or missing pieces of data; not every column is worth studying. Other weaknesses include:  

- The **size** of the dataset: this makes it difficult to load in data and push it to GitHub because the file sizes are so large.  
- **Missing** (NA) **values**: with the large array of columns, some features simply do not apply to certain attacks or there is no information about that feature of an attack for a given country or entry.

### 3.3 Data Wrangling
_Please refer to 1.3.1_ 

### 3.4 Refer to Appendix

See Appendix 1: Data Dictionary. 

## 4.0 INFORMATION VISUALIZATIONS 

### 4.1 Map  
The first visualization is a map with points that scale in size depending on the number of casualties in different countries. Due to the global nature of our data, a geographical map seemed like the most intuitive visualization. By also changing the size of the points on the map depending on the number of casualties, viewers can see the impact of terrorism in each country/region at a glance.  For further depth, two interactive features were added - a dropdown that allows users to select the type of attack they would like to study, as well as the ability to view additional details when users click on individual attacks on the map. This allows users to view the impact of specific types of attacks on certain regions such as the number of people wounded and the number of people killed during those attacks.  Hopefully, viewers will be able to leave with a geographical sense of how different attacks impact different regions after interacting with this map.  

### 4.2 Bar Graph Comparison  
This is an interactive visualization in which users are able to select two different countries and compare the number of people impacted by a terrorist attack in that country and the attack types. Each bar represents the total number of people impacted (sum of deaths and injuries) by terrorist attacks in the specified country. Within each bar, the user can see a visual comparison of the number of people wounded versus the number of people killed in that attack by the different attack types used in that country. The graph also shows the attack types that have been used in the specified country and the correlating sums of information about casualties and injuries. Additionally, the graph is ordered such that the number of people impacted appears in increasing order. In this way, users are able to easily identify which attack types have had the greatest or least amount of impact on individuals in that country. Overall, the bar graph offers a visual comparison of the impact of different attack types on individuals in specific countries.  

### 4.3 Data Table  
For our second information visualization, we used a table. Our table displays 13 different bits of summary information about the overall dataset. The summary information changes depending on which region of the world the user selects. The table includes information such as the extremes (minimum and maximum) of certain variables (i.e. the number of total attacks in a certain region), showing which areas have been more prone to terror attacks and which areas have had fewer attacks. The user also has the ability to search the table and through entries in the table if they are looking for very specific data. This table allows the user to view more specific summary data about the issue.


## 5.0 TECHNICAL DESCRIPTION OF SHINY APPLICATION   

### 5.1 Loading the Data

The datasets used are loaded in a .csv file. 
Certain data were selected and filtered, and were put into a shape (.shp) file. This shape file is used to create the world map and to determine the borders of each country. If a user clicks on a country it will display the statistics for that data. The data in the set is then used by leaflet to determine which area of the map will display which information. 

### 5.2 Libraries Used

**Dplyr** is used to trim and wrangle the data such that only relevant columns are displayed in the data set. It is also used to select and filter certain columns and rows to obtain specific information for the leaflet popups.  

**ggplot2** is a library used to format various elements of the map and to generate the bar graphs that compare impacts of terrorism between two different countries.  

**Leaflet** is used to create the map and the popup widget that displays information about terror attacks in different areas of the world.  

**Raster** is used to help generate spatial components of the map.  

**Rgdal** is used to help generate spatial components of the map.  

**Shiny** is used to create the UI and server.  

**Shinythemes** is a supplemental library that is used to change the color scheme and overall aesthetic theme of the Shiny application.  

### 5.3 Organization of Code

The home directory contains analysis, data, and images folders, a gitignore file, a README.r file, and the server and ui files. 
The analysis file contains R files used for data wrangling (i.e. calculating total casualties by region). The data file contains the datasets used in the project, including the original datasets and smaller, cleaner datasets that are easier to process for analysis. The images folder contains images used in the reports and in other parts of the project.

### 5.4 Questions to Answer and Explore

- How many people are affected by various attack types? (Measured by number of casualties, injuries, property damage)
- Which attack types are most prevalent in different countries? 
- At a glance, which area of the world seems to be impacted most by terrorist attacks? 
- What groups of people are most affected or most targeted by terrorist attacks?

## 6.0 CONCLUSION

### 6.1 Strengths and Weaknesses

### 6.1.1 Strengths
We have an incredibly robust dataset with a great deal of data that has the potential to answer a number of interesting questions. Our team also has the critical thinking and coding skills to overcome any looming obstacles that we will likely encounter as we further develop our final project. This project also has a great deal of potential to explore various aspects of terrorism (time, location, type of attack and target, casualties. etc.).  

### 6.1.2 Weaknesses
The scope of the project may still be too broad; however, we are working to think of ways to narrow this scope and focus our analysis on more specific, interesting, and meaningful questions using the datasets we have obtained. Additionally, with regards to the data specifically, we fear that the data may focus more on more heavily publicized attacks in larger or news-worthy countries as the data collected was based on articles and publications. Smaller, poorer countries may not be as well represented in the data since they may not have the resources to publish as much as other countries or may not receive as much attention.

### 6.2 Main Lessons Learned
We learned that global terrorism is immensely complex and that it is much too broad, complex, and large of an issue to make causal or predictive claims and analyses. However, through discussion about research questions, data visualizations, and future plans, we have learned to develop our critical thinking and coding skills. Another noteworthy lesson we learned was that it can be difficult to find datasets to fit our needs, and sometimes, we need to challenge ourselves to work with what we have available and to generate creative solutions.

### 6.3 Future Work
If we had more time and resources, our group would be interested in exploring how the amount of publicity and media coverage of terrorist attacks in different countries varies across countries and regions of the world. It would also be interesting to explore how terrorist attacks impact global economic trends as tensions between countries would likely affect trade.
Other, perhaps more skilled and experienced researchers and data scientists could build on this project by exploring the causal and predictive claims that our group cannot make.
 


## 7.0 ACKNOWLEDGEMENTS 

We wish to acknowledge the help provided by Benjamin Xie in the development of this project.

## 8.0 REFERENCES 

Cato Institute. (2017). Cato 2017 Human Freedom Index (Version 3). [Data File]. Retrieved from https://www.kaggle.com/doyouevendata/cato-2017-human-freedom-index#cato_2017_human_freedom_index.csv  

Data Society. (2016). Global Terrorism Data. [Data File]. Retrieved from https://data.world/data-society/global-terrorism-data/contributors  

Institute for Economics & Peace. (2018). Retrieved from http://visionofhumanity.org/indexes/terrorism-index/  

Loayza, N. (2016, July 29). How to defeat terrorism: Intelligence, integration, and development. Retrieved from https://www.brookings.edu/blog/future-development/2016/07/25/how-to-defeat-terrorism-intelligence-integration-and-development/.


## 9.0 LINKS
Link to README.md: https://github.com/jctroyer/Info-201-Final-Project/wiki/Project-Overview  
Link to Shiny App: https://jctroyer.shinyapps.io/Info-201-Final-Project/

## APPENDIX 1: DATA DICTIONARY  


`r table`

## APPENDIX 2: REFLECTIONS 

**Joseph:** I usually like to be the one behind a computer all day coding, however this is the first time I was in a team environment with code involved. As a developer of a team it becomes a lot more stressful with the time crunch, which is why I have a ton of respect for my groupmate, Dorothy. In addition, there are repercussions if something was not done properly and in a timely manner. This is a lot more nerve wrecking than the hackathons I have participated in, where they are very forgiving because it is just usually one weekend. An issue that did come up is that it is a little difficult to find a proper time to meet with everyone, instead it has been more of a one on one rather than a full team meeting. This project does help a little in seeing how a PM operates. Seeing what it takes to set up meetings and deadlines for certain tasks are encouraged to move through milestones swiftly.  

**Jazmynn:** The project developed slowly, but surely. I found it difficult to narrow the scope of the project and devise concise yet meaningful research questions that did not extend beyond the limits of our class. It was also difficult to find datasets that provide relevant and useful information to complement the main Global Terrorism Database (GTD) datasets we intend to use. These issues were resolved with the help and feedback of Benji, our teaching assistant.  
In other regards, there were parts of the development process in which I contributed more to writing rather than designing and coding, and other parts when my role was flipped. As a result, this experience challenged my critical thinking, coding, and problem-solving skills.  
With regards to the Shiny app, I did encounter some challenges with deploying the app, debugging, rendering visualizations, creating working widgets, and piecing everyone’s code together. Although the debugging process was long and tedious, it was immensely satisfying to be able to successfully publish and deploy the final Shiny app once all the troubleshooting was complete. Bugs and errors can be challenging, but tackling those problems and searching for solutions are skills that I look forward to further developing as a coder. 

**Dorothy:** This project has been both immensely challenging and fun. Though I was constantly frustrated with the long process of debugging, I feel like my self-teaching skills are one of my skills that have greatly increased.  Because I encountered many more roadblocks creating our map than I thought I would, I ended up doing a lot of research into Shiny data visualizations (specifically maps), allowing me to learn about things such as .shp files which I hadn’t encountered before.  Additionally, I think this stage of the project has allowed me to enjoy coding much more, as I really appreciate being able to see a visual product of all the work we’ve been doing and I also feel much more confident in R. I have also realized that I have almost too much left to learn, and that to make things easier in the future, I will try to have a deeper understanding of the code and their underlying processes before using them.  This would definitely allow understanding errors in the output much easier, and maybe I wouldn’t have had to pull my hair out over the choropleth map before giving up.  However, this project has definitely helped me develop my identity as a thinker and coder and allowed me to be more confident in tackling coding issues that I don’t know.

## APPENDIX 3: USE OF ENVISIONING CARDS  

The envisioning cards were used to discuss the direct and indirect stakeholders involved in global terrorist attacks, explore the social and ethical implications of the problem, and consider the strengths and weaknesses of the datasets to be used in the project. 
The cards that were used include:  

- **Direct Stakeholders**: used to brainstorm and consider direct stakeholders.  
- **Indirect Stakeholders**: used to brainstorm and consider indirect stakeholders.  
- **Elicit Stakeholders Views and Values**: used to further consider the stakeholders of the project, how global terrorism affects them, and why they may care about this project or about the overall issue this project seeks to address.  
- **Crossing National Boundaries**: since the project addresses global terrorism, this card was used to consider how this issue and this project may be useful (or perhaps unuseful) in other countries.  
- **Evaluate User Experience of Values**: used to consider the design of our visualizations, with regards to what insights the user may gain from different visualizations and why they may care.  
- **Value Tensions**: used to consider the target and attack types mentioned in the dataset to inform our formation of research questions and our consideration of the problem statement.  
- **Consider Key Values at Stake**: since terrorism is a result of conflicting or differing ideological values, this was used to consider the values of different stakeholders from different regions of the world in order to form our problem statement.  
- **Work of the Future**: used to evaluate the dataset used for the project. Also used to consider the design of visualizations, to consider the subsets of the dataset the project would use, and to consider future ramifications of this project.  
- **Obsolescence**: used to consider the strengths and weaknesses of the dataset.